# -*- coding: utf-8 -*-
"""SELF_simple_linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x8Bn1BPC8EdvgwVmhYUUByhZqlqJYfPq

# Simple Linear Regression

## Importing the libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## Importing the dataset"""

dataset = pd.read_csv('Salary_Data.csv')
X= dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

"""## Splitting the dataset into the Training set and Test set"""

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

"""## Training the Simple Linear Regression model on the Training set"""

from sklearn.linear_model import LinearRegression
regressor= LinearRegression()
regressor.fit(X_train,y_train)

"""## Predicting the Test set results"""

y_pred=regressor.predict(X_test)

"""## Visualising the Training set results"""

plt.scatter(X_train,y_train,color='red')
plt.plot(X_train,regressor.predict(X_train),color='blue')
plt.title('salary VS experience(TRAINING SET)')
plt.xlabel('years of experience')
plt.ylabel('salary')
plt.show()

"""## Visualising the Test set results"""

plt.scatter(X_test,y_test,color='red')
plt.plot(X_train,regressor.predict(X_train),color='blue')
plt.title('salary VS experience(Test SET)')
plt.xlabel('years of experience')
plt.ylabel('salary')
plt.show()

predicted_salary = regressor.predict([[X_test[0, 0]]])
print(predicted_salary)
# Get the intercept (b0)
b0 = regressor.intercept_

# Get the coefficient (b1)
b1 = regressor.coef_[0]  # Since it's a simple linear regression, there's only one coefficient

print(f"Final Regression Equation: y = {b0:.2f} + {b1:.2f}x")